[lint]
# 1. Enable flake8-bugbear (`B`) rules, in addition to the defaults.
select = ["E4", "E7", "E9", "F", "B"]

# 2. Avoid enforcing line-length violations (`E501`)
ignore = ["F403", "F405"]

# 3. Avoid trying to fix flake8-bugbear (`B`) violations.
unfixable = ["B"]
